# Generated by Django 2.2.7 on 2019-11-23 09:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('app', '0002_nice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nice',
            name='id',
        ),
        migrations.AlterField(
            model_name='nice',
            name='photo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False,
                                    to='app.Photo'),
        ),
    ]
